SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE m
WHERE MONTH(DATE_OF_BIRTH) = '03'
AND GENDER = 'W'
AND TLNO is NOT NULL
ORDER BY MEMBER_ID ASC